apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
  labels:
    app: frontend

spec:
  updateStrategy:
    type: OnDelete

  template:
    metadata:
      name: pod-web-server
      labels:
        apps: my-app
        tier: frontend
    spec:
      containers:
        - name: my-container-nginx
          image: nginx
      nodeSelector:
        diskType: ssd

  selector:
    matchLabels:
      apps: my-app


# Nessa configuração com OnDelete o ds não ira substituir o Pod, ele ira forçar vc deletar o pod de forma imperativa 
# ou seja vc ira ter que digitar o comando $ kubectl delete pods [nome do pod] 
# e apos ser deletado ele criara o novo pod com as configuracoes novas
