kind: ConfigMap
apiVersion: v1
metadata:
  name: my-cm
data:
  #Connection database config # dessa maneira ele cria arquivos properties com mais de uma configuração dentro dele
  my.config.db: |
    database: mariadb
    database_uri: mariadb://localhost:3306
  test.field: hello
  test2: hello2.1
  test3: hello3.0
immutable: true # esse atributo não deixa mudar as variaveis de configuração, caso seja removido o aquivo configmap os pods não sofreram alterações caso queira os podes precisaram ser recriados
