apiVersion: v1
kind: Service
metadata:
  name: my-eps-service
spec:
  ports:
    - name: http
      port: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-eps
  labels:
    kubernetes.io/service-name: my-eps-service  # esta é a instrução tem q ter o mesmo nome do servico na linha 4
addressType: IPv4
endpoints:
- addresses:
  - 10.244.0.10 #Apache
ports:
- name: http
  port: 80
  protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-eps-2
  labels:
    kubernetes.io/service-name: my-eps-service # esta é a instrução tem q ter o mesmo nome do servico na linha 4
addressType: IPv4
endpoints:
- addresses:
  - 10.244.0.11 #Nginx
ports:
- name: http
  port: 80
  protocol: TCP



# "endpointSlice" pode ser aplicado IPv4, IPV6 e FQDN(Fully Qualified Domain Name)
# enquanto que o "endpoint" apenas aplica IPv4 e IPv6

# comando para listar os endpointSlice
# $ kubectl get endpointslice