apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth # este tipo indica q tem que ter obrigatoriamente os campos username e password, caso não tenha ele não cria o secret, este campo é immutable caso tenha q mudar tem que deletar o secret e criar novamente

data:
  username: YWRtaW4K
  password: UGFzcy0xMjMK
  extra-key: UGFzcy0xMjMK

stringData:
  extra2: value2
