apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  user: YWRtaW4=  #chave e valor codificado em base64 'admin'
  pass: TXktcGFzcy0xMjM= #chave e valor codificado em base64 'My-pass-123'
stringData:
  my-database-name: mysql # chave valor sem a conversão em base64


#comando em linux para gerar a base64 de um valor
# $ echo -n 'admin' | base64


#comando em linux para decodificar o base64 de um valor
# $ echo -n 'YWRtaW4=' | base64 --decode && printf "\n"

#comando para mostrar o describe do secret
# $ kubectl describe secret my-secret

# o Secret pode ter no máximo 1024kb
# também tem a possibilidade de usar immutable: true