apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  user: YWRtaW4=
  pass: TXktcGFzcy0xMjM=
stringData:
  my-database-name: mysql
---

kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-vol-env
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - secretRef:
        name: my-secret
    volumeMounts:
    - name: my-vol
      mountPath: "/etc/my-vol"
      readOnly: true

  volumes:
  - name: my-vol
    secret:
      secretName: my-secret


# comando para entrar no pode e executar o comando env
# $ kubectl exec -it  pod-secret-vol-env -- env

# comando para entrar no pode e verificar se os volume criado possui os arquivos criados
# $ kubectl exec -it  pod-secret-vol-env -- ls /etc/my-vol

# comando para entrar no pode mostar o valor do arquivo o k8s ira criar dentro do volume os arquivos admin, pass e my-database-name
# que são o conteudo configurado no secret, caso seja mudado os valores precisa ser reiniciado o pod
# $ kubectl exec -it  pod-secret-vol-env -- cat /etc/my-vol/user  && printf "\n"
