kind: Pod
apiVersion: v1
metadata:
  name: pod-secret-vol-env
spec:
  containers:
  - name: my-container
    image: nginx
    envFrom:
    - secretRef:
        name: my-secret
        optional: true # indica que o carregamento do secret é opcional podendo existir ou não
    volumeMounts:
    - name: my-vol
      mountPath: "/etc/my-vol"
      readOnly: true

  volumes:
  - name: my-vol
    secret:
      secretName: my-secret
      optional: true # indica que o carregamento do secret é opcional podendo existir ou não
